#!/bin/sh

print_workspaces() {
    windows=$(
        hyprctl workspaces -j \
            | jq 'map({key: .id | tostring, value: .windows}) | from_entries'
    )
    seq 1 10 \
        | jq \
            --argjson windows "$windows" \
            --slurp \
            -Mc 'map(tostring) | map({id: ., windows: ($windows[.]//0)})'
}

print_workspaces

socat \
    -u "UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" \
    - \
    | while read -r _; do
        print_workspaces
    done

