gui:
  theme:
    selectedLineBgColor:
      - underline
    selectedRangeBgColor:
      - underline
  mainPanelSplitMode: horizontal

git:
  pagers:
    # - useExternalDiffGitConfig: true
    - pager: delta --dark --paging=never
  disableForcePushing: true
  overrideGpg: true

customCommands:
  - key: 'ŝ'
    context: 'global'
    command: 'kill "$PPID"'
  - key: 'G'
    context: 'global'
    command: 'zsh -ci gh-switch'
os:
  editPreset: 'nvim'

promptToReturnFromSubprocess: false

