#!/bin/sh

# Set `init=1` if first reload since X11 was started
# `wm-init` file created by xinit
if [ -e "$HOME/.local/share/wm-init" ]; then
    init=1
    rm -f "$HOME/.local/share/wm-init"
fi

scripts="$HOME/scripts/cmd"
sxhkd_scripts="$HOME/.config/sxhkd/scripts"

if pgrep -x sxhkd > /dev/null;
    then killall -SIGUSR1 sxhkd
    else sxhkd &
fi
if pgrep -x polybar > /dev/null;
    then killall -SIGUSR1 polybar
    else polybar &
fi

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config window_gap 4
if [ -n "$init" ]; then
    bspc config border_width 2
fi

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

rect_large='1400x950+0+0'
bspc rule -a kitty-btop      state=floating center=true rectangle="$rect_large"
bspc rule -a *:Mail          state=floating center=true rectangle="$rect_large"
bspc rule -a Spotify         state=floating center=true rectangle=850x700+0+0
bspc rule -a vesktop         state=floating center=true rectangle="$rect_large"
bspc rule -a TelegramDesktop state=floating center=true rectangle="$rect_large"
bspc rule -a Windscribe2     state=floating center=true border=off

if [ -n "$init" ]; then
    betterbird &
    spotify &
    windscribe &
fi

xsetroot -cursor_name left_ptr

if [ -n "$init" ]; then
    setxkbmap -layout au
fi

device_touchpad='MSFT0001:01 06CB:CE44 Touchpad'

# Enable touchpad while keys are pressed
xinput set-prop "$device_touchpad" 'libinput Disable While Typing Enabled' 0
# Enable natural scrolling
xinput set-prop "$device_touchpad" 'libinput Natural Scrolling Enabled'    1

monitors auto

if [ -n "$init" ]; then
    $scripts/bt status || pactl set-sink-volume @DEFAULT_SINK@ 0%
fi

$sxhkd_scripts/picom-exec restart &

bg-change 300 &

nm-applet --no-agent &

clipcatd &

flameshot &

killall unclutter
unclutter -idle 2 &

if [ -n "$init" ]; then
    bspc rule -a LibreWolf desktop='^2' follow=off --one-shot
    librewolf &
fi


