#!/bin/sh

scripts="$HOME/scripts/cmd"
sxhkd_scripts="$HOME/.config/sxhkd/scripts"

if pgrep -x sxhkd > /dev/null;
    then killall -SIGUSR1 sxhkd
    else sxhkd &
fi
pgrep -x polybar > /dev/null || polybar &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

setxkbmap -layout au

device_touchpad='MSFT0001:01 06CB:CE44 Touchpad'

# Enable touchpad while keys are pressed
xinput set-prop "$device_touchpad" 'libinput Disable While Typing Enabled' 0
# Enable natural scrolling
xinput set-prop "$device_touchpad" 'libinput Natural Scrolling Enabled'    1

monitors auto

$scripts/bt status || pactl set-sink-volume @DEFAULT_SINK@ 0%

$sxhkd_scripts/picom-exec restart &

bg-change 300 &

nm-applet --no-agent &

clipcatd &

flameshot &

bspc config window_gap 4 &

bspc rule -a LibreWolf desktop='^2' follow=off -o
pgrep -x librewolf > /dev/null || librewolf &


