#!/bin/sh

ws="$1"
if [ -z "$ws" ]; then
    echo 'exec-workspace: missing workspace argument.'
    exit 1
fi
class="$2"
if [ -z "$ws" ]; then
    echo 'exec-workspace: missing class argument.'
    exit 1
fi
shift 2
cmd=$*
if [ -z "$cmd" ]; then
    echo 'exec-workspace: missing program command.'
    exit 1
fi

eval "$cmd" &

attempts=0
max_attempts=100
while [ "$attempts" -lt "$max_attempts" ]; do
    attempts=$((attempts+1))
    sleep 0.05
    i3-msg "[class=\"${class}\"] focus"
    if [ "$?" = 0 ]; then
        sleep 0.05
        i3-msg "move container to workspace number $ws"
        exit 0
    fi
done
notify-send "exec-workspace: failed to focus '$program', after $max_attempts attempts"
exit 69

