#!/bin/sh

default() {
    i3-msg kill
}

class="$(xdotool getactivewindow getwindowclassname)"

case "$class" in
    # Kill background process as well
    # This program is a scratchpad
    'discord')
        default
        killall 'Discord'
        ;;

    # Add custom rules here...

    *) default ;;
esac

