#!/bin/sh

player='spotify'
bar_color="#7f7fff"

song="$(playerctl -p "$player" metadata -f '{{title}} - {{artist}}')"
time="$(playerctl -p "$player" metadata -f '{{duration(position)}} / {{duration(mpris:length)}}')"
percent="$(playerctl -p "$player" metadata -f '{{position / mpris:length * 100}}')"
status=''
[ "$(playerctl -p "$player" status)" = 'Playing' ] && status=''

~/scripts/cmd/bt status && charge="|  $(~/scripts/cmd/bt charge)"

dunstify -r 9238 -t 1000 "$song" "$status $time $charge" -h int:value:"${percent%.*}" -h string:hlcolor:"$bar_color"

