#!/usr/bin/env bash

# File:           scratchpad_script.sh
# Description:    Script to toggle or create scratchpad windows
# Author:       RayZ0rr, Reinaldo Molina
# Created:        Fri Jan 18 2019 12:20

############# GLOBVAR/PREP ###############

name="$1"
Usage="\
  Usage: $(basename $0) <name> <command>
  <name>    : name the window has
  <command> : command used to launch window in case doesnt exist
  E.g.:  $(basename $0) terminal \"$TERMINAL --title=terminal\"
  "

# Terminal width and position variables ( you may use these but currently not used in script )
# host=`hostname`
# width=1920
# height=440
# posy=32
# if [ "$host" = "predator" ]; then
#   width=3840
#   height=800
#   posy=48
# fi

############## USGCHECKS #################

if [[ $# -lt 1 || "$1" =~ ^(-h|--help)$ || $# -gt 2 ]]; then
  echo "$Usage"
  exit 1
fi

################ MAIN ####################

visible_wid="$(xdotool search --onlyvisible --classname "${name}" | tail -1 2> /dev/null)"

# Use `class` for thunderbird
if [ "$name" = 'thunderbird' ]; then
    selector='class';
else
    selector='instance';
fi

if [[ -z "$visible_wid" ]]; then # If the scratchpad window is not visible
  wid="$(xdotool search --classname "${name}" | tail -1 2> /dev/null)"
  if [[ -z "$wid" ]]; then       # If the scratchpad window does not exist
    if [[ $# -ne 2 ]]; then    # If a command to launch it was not provided
      echo "${name} not found. A command was not provided to launch it."
      exit 2
    fi

    # Program arguments are ignored
    # Forking process, so this script is not halted until program closes
    # This does not catch any errors! (I think)
    echo "${name} not found. Executing: '${2}'."
    eval "$2" &

    # Constantly try to show newly spawned window
    # Much more reliable than waiting with `xdotool`
    attempts=0
    max_attempts=100
    while [ "$attempts" -lt "$max_attempts" ]; do
        attempts=$((attempts+1))
        sleep 0.05;

        # Re-apply window config
        lua "$HOME/.config/i3/scripts/scratchpad.lua" init

        i3-msg "[$selector=\"${name}\"] scratchpad show; \
                [$selector=\"${name}\"] move position center"
        if [ "$?" = 0 ]; then
            exit 0;
        fi
    done
    notify-send "scratchpad: failed to show '$name', after $max_attempts attempts"
    exit 69
  fi

  echo "${name} found. Showing scratchpad."
  i3-msg "[$selector=\"${name}\"] scratchpad show; \
    [$selector=\"${name}\"] move position center"
  exit $?
fi

echo "Hiding instance of ${name}."
i3-msg "[$selector=\"${name}\"] scratchpad show"
exit $?
