#!/bin/sh

real_key="$1"
override_key="$2"

mod_key=Alt

# Release both key variants
xdotool keyup "$real_key"
xdotool keyup "$override_key"

xdotool keyup "$mod_key"

xdotool key --clearmodifiers "$override_key"

xdotool keydown "$mod_key"

