#!/bin/sh

default() {
    xdo close
}

class="$(xdotool getactivewindow getwindowclassname)"

case "$class" in
    # Kill background process as well
    # This program is a scratchpad
    'discord')
        default
        killall 'Discord'
        ;;
    'vesktop')
        default
        killall 'electron'
        ;;

    # Add custom rules here...

    *) default ;;
esac

