onboarding = false

[theme]
name = "vesper"
auto_switch = false

[ui.toast.clipboard]
enabled = true
position = "bottom-right"

[experimental]
kitty_graphics = true

[keys]
focus_pane_left = ["alt+h"]
focus_pane_right = ["alt+l"]
focus_pane_up = ["alt+k"]
focus_pane_down = ["alt+j"]
previous_tab = ["alt+i"]
next_tab = ["alt+o"]
switch_tab = ["alt+1..9"]

[[keys.command]]
key = "prefix+g"
type = "pane"
command = "lazygit"
description = "run lazygit"

