[manager]
prepend_keymap = [
    # Esperanto keys
    { on = [ "ŝ" ], run = "quit", desc = "Quit (eo)" },
    { on = [ "ĉ" ], run = "yank --cut", desc = "Cut (eo)" },

    # Shell
    { on = [ ":" ], run = "plugin custom-shell", desc = "Run shell commmand (zsh)" },

    # Copy
    { on = [ "c", "f" ], run = "shell --confirm --block 'cb copy $@'", desc = "Copy file to clipboard" },
    { on = [ "c", "c" ], run = "shell --confirm --block 'cat $@ | cb copy'", desc = "Copy text to clipboard" },
]

