[opener]
default = [
    { run = '$HOME/scripts/cmd/open "$@"', desc = "Open with default program" }
]
ignore = [
    { run = 'true', desc = "(Do not open)" }
]

browser = [
    { run = '$BROWSER "$@"', desc = "Open with browser" }
]

nsxiv = [
    { run = 'nsxiv "$@"', desc = "Open with Nsxiv" },
]
inkscape = [
    { run = 'inkscape "$@"', desc = "Open with Inkscape" },
]
gimp = [
    { run = 'gimp "$@"', desc = "Open with Gimp" },
]
vlc = [
    { run = 'devour vlc "$@"', desc = "Open with VLC" },
]
document = [
    { run = 'devour libreoffice "$@"', desc = "Open with LibreOffice" },
]

copy-file = [
    { run = 'cb copy $@', desc = "Copy file to clipboard" },
]
copy-text = [
    { run = 'cat $@ | cb copy', desc = "Copy text to clipboard" },
]

[open]
prepend_rules = [
    # "edit" enters the file, instead of opening in new window, so prefer this
    { mime = "text/*", use = [ "edit", "default", "copy-text" ] },

    { mime = "image/svg*", use = [ "default", "nsxiv", "copy-file" ] },
    { mime = "image/x-xcf", use = [ "default", "nsxiv", "copy-file" ] },
    { mime = "image/*", use = [ "nsxiv", "inkscape", "gimp", "copy-file" ] },

    { mime = "video/*", use = [ "default", "vlc" ] },
    { mime = "audio/*", use = [ "default", "vlc" ] },

    { mime = "application/pdf", use = [ "default", "browser" ] },

    { mime = "inode/directory", use = [ "ignore" ] },

    { mime = "application/*.document", use = [ "document", "default" ] },

    # Executables
    { mime = "application/x-pie-executable", use = [ "ignore" ] },
]

append_rules = [
    { name = "*", use = [ "default" ] }
]

