[opener]
nsxiv = [
    { run = 'nsxiv "$@"', desc = "Open with Nsxiv" },
]
inkscape = [
    { run = 'inkscape "$@"', desc = "Open with Inkscape" },
]
gimp = [
    { run = 'gimp "$@"', desc = "Open with Gimp" },
]
copy-file = [
    { run = 'cb copy $@', desc = "Copy file to clipboard" },
]
copy-text = [
    { run = 'cat $@ | cb copy', desc = "Copy text to clipboard" },
]
nvim-dir = [
    { run = """
        nvim +'lua require("yazi").yazi()'
    """, desc = "Open directory in Neovim", block = true }
]

[open]
prepend_rules = [
    { mime = "image/svg*", use = [ "inkscape", "nsxiv", "copy-file", "reveal" ] },
    { mime = "image/*", use = [ "nsxiv", "inkscape", "gimp", "copy-file", "reveal" ] },

    { mime = "inode/directory", use = [ "nvim-dir" ] },
]

