[opener]
nsxiv = [
    { run = 'nsxiv "$@"', desc = "Open with Nsxiv" },
]
inkscape = [
    { run = 'inkscape "$@"', desc = "Open with Inkscape" },
]
copy-file = [
    { run = 'cb copy $@', desc = "Copy file to clipboard" },
]
copy-text = [
    { run = 'cat $@ | cb copy', desc = "Copy text to clipboard" },
]

[open]
prepend_rules = [
    { mime = "image/*", use = [ "nsxiv", "inkscape", "copy-file", "reveal" ] },
    { mime = "text/*", use = [ "edit", "copy-text", "reveal" ] },
]

