[opener]
nsxiv = [
    { run = 'nsxiv "$@"', desc = "Open with Nsxiv" },
]
inkscape = [
    { run = 'inkscape "$@"', desc = "Open with Inkscape" },
]
copy = [
    { run = 'cb copy $@', desc = "Copy content to clipboard" },
]

[open]
prepend_rules = [
    { mime = "image/*", use = [ "nsxiv", "inkscape", "copy", "reveal" ] },
]

