[opener]
default = [
    { run = '$HOME/scripts/cmd/open "$@"', desc = "Open with default program" }
]
ignore = [
    { run = 'true', desc = "(Do not open)" }
]

browser = [
    { run = '$BROWSER "$@"', desc = "Open with browser" }
]

swiv = [
    { run = 'swiv -B "#000000" "$@"', desc = "Open with Swiv" },
]
inkscape = [
    { run = 'inkscape "$@"', desc = "Open with Inkscape" },
]
gimp = [
    { run = 'gimp "$@"', desc = "Open with Gimp" },
]
mpv = [
    { run = 'mpv --force-window "$@"', desc = "Open with MPV" },
]
vlc = [
    { run = 'devour vlc "$@"', desc = "Open with VLC" },
]

wine = [
    { run = 'wine "$@"', desc = "Run with WINE" },
]

musescore = [
    { run = 'mscore "$@"', desc = "Open with MuseScore" },
]

copy-file = [
    { run = 'cb copy $@', desc = "Copy file to clipboard" },
]
copy-text = [
    { run = 'cat $@ | cb copy', desc = "Copy text to clipboard" },
]

[open]
prepend_rules = [
    # "edit" enters the file, instead of opening in new window, so prefer this
    { mime = "text/*", use = [ "edit", "default", "copy-text" ] },

    { mime = "image/svg*", use = [ "default", "swiv", "copy-file" ] },
    { mime = "image/x-xcf", use = [ "default", "swiv", "copy-file" ] },
    { mime = "image/*", use = [ "swiv", "inkscape", "gimp", "copy-file" ] },

    { mime = "video/*", use = [ "mpv", "vlc" ] },
    { mime = "audio/*", use = [ "mpv", "vlc" ] },

    { mime = "application/pdf", use = [ "default", "browser" ] },
    { mime = "application/epub*", use = [ "default", "browser" ] },

    { mime = "inode/directory", use = [ "ignore" ] },

    { name = "*.mscz", use = [ "musescore" ] },

    # Executables
    { mime = "application/x-pie-executable", use = [ "ignore" ] },
    { mime = "application/vnd.microsoft.portable-executable", use = [ "wine" ] },

    # TODO: Use mime type `application/x-subrip`
    { name = "*.srt", use = [ "edit", "default", "copy-text" ] },
]

append_rules = [
    # { name = "*", use = [ "default" ] }
]

