#!/bin/sh

real_key="$1"
override_key="$2"

mod_key=Alt

xdotool keyup "$real_key"
xdotool keyup "$mod_key"

xdotool key --clearmodifiers "$override_key"

# sleep 0.5

# xdotool key     "$mod_key"
# xdotool keyup   "$mod_key"
# xdotool keydown "$mod_key"
# xdotool keyup   "$mod_key"

